# syntax=docker/dockerfile:1

FROM eclipse-temurin:25-jdk AS build
WORKDIR /workspace

COPY .mvn .mvn
COPY mvnw pom.xml ./
COPY src/main src/main

RUN ./mvnw -Dmaven.test.skip=true package

FROM eclipse-temurin:25-jre
WORKDIR /app

COPY --from=build /workspace/target/phoenix-0.0.1-SNAPSHOT.jar /app/phoenix.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/phoenix.jar"]
