insert into exercises (
    id,
    scope,
    owner_user_id,
    name,
    name_pt,
    movement_pattern,
    body_area,
    equipment_type,
    default_safety_notes,
    active
) values
('f117dd74-2a0f-5c5a-8073-bb907004cac2', 'GLOBAL', null, 'Chest Press (Machine)', 'Supino na maquina / Chest press', 'HORIZONTAL_PUSH', 'CHEST', 'MACHINE', 'Back supported, scapulae set, shoulder stays on bench.', true),
('6ee2045b-a8d8-5f5e-9281-abbd58d6c310', 'GLOBAL', null, 'Seated Row (Cable)', 'Remada sentada no cabo', 'HORIZONTAL_PULL', 'BACK', 'CABLE', 'Stable torso, no lumbar swing.', true),
('ec05a7db-9dd7-5ef1-9c74-35549d7af332', 'GLOBAL', null, 'Incline Chest Press (Machine)', 'Supino inclinado na maquina', 'INCLINE_PUSH', 'UPPER_CHEST', 'MACHINE', 'Comfortable range, no right-shoulder pain.', true),
('f3abfc0d-c301-5a18-9cb0-b638b693d741', 'GLOBAL', null, 'Lat Pulldown (Cable)', 'Puxada alta aberta', 'VERTICAL_PULL', 'LATS', 'CABLE', 'Pull to upper chest, no body swinging.', true),
('791f2483-9fc2-57f1-8a16-199b88469bc8', 'GLOBAL', null, 'Lateral Raise (Machine)', 'Elevacao lateral maquina', 'SHOULDER_ABDUCTION', 'LATERAL_DELTS', 'MACHINE', 'Controlled reps, no momentum.', true),
('2435f593-f6b4-51c5-87eb-47591969ecfa', 'GLOBAL', null, 'Triceps Pushdown (Cable - Straight Bar)', 'Triceps polia barra reta', 'ELBOW_EXTENSION', 'TRICEPS', 'CABLE', 'Fixed elbows, avoid torso cheating.', true),
('f6b48a03-941c-59a0-b754-575550c1e58d', 'GLOBAL', null, 'Leg Extension (Machine)', 'Cadeira extensora', 'KNEE_EXTENSION', 'QUADS', 'MACHINE', 'Controlled descent, no bouncing.', true),
('b8a12d73-f459-5d50-8e51-a9f99af4139f', 'GLOBAL', null, 'Seated Leg Curl', 'Mesa flexora sentada', 'KNEE_FLEXION', 'HAMSTRINGS', 'MACHINE', 'Do not lift hips, controlled return.', true),
('46bfb534-b524-5457-af25-7c043a9aaa7c', 'GLOBAL', null, 'Hip Thrust (Machine or Smith)', 'Elevacao pelvica / Hip Thrust', 'HIP_EXTENSION', 'GLUTES', 'MIXED', 'Neutral spine, no lumbar hyperextension.', true),
('8db46c85-c429-56e2-9ce3-e0bcc54dec52', 'GLOBAL', null, 'Bulgarian Split Squat', 'Afundo bulgaro', 'UNILATERAL_SQUAT', 'QUADS', 'MIXED', 'Prioritize stability, no hip pain.', true),
('2f903b98-8fdc-56b7-9f58-ed250c5b61e2', 'GLOBAL', null, 'Standing Calf Raise', 'Panturrilha em pe', 'CALF_RAISE', 'CALVES', 'MIXED', 'Full range, controlled top hold.', true),
('c73158c2-5af4-5ebf-bffd-27e2f7691055', 'GLOBAL', null, 'Cable Crunch', 'Abdominal no cabo', 'TRUNK_FLEXION', 'ABS', 'CABLE', 'Flex spine, do not pull with arms.', true),
('a547a1df-0763-5fbc-8e2f-96890417fa72', 'GLOBAL', null, 'Iso-Lateral Row (Machine)', 'Remada iso-lateral maquina', 'HORIZONTAL_PULL', 'BACK', 'MACHINE', 'Chest supported if possible, do not rotate torso.', true),
('8aaec79d-c432-5ca7-9c70-024f86caa2c6', 'GLOBAL', null, 'Lat Pulldown - Underhand (Cable)', 'Puxada alta pegada supinada', 'VERTICAL_PULL', 'LATS', 'CABLE', 'Firm torso, do not throw body backward.', true),
('7c7555e5-1519-5c2f-8909-c86e99dbb0a7', 'GLOBAL', null, 'Cable Crossover', 'Crucifixo / crossover no cabo', 'CHEST_FLY', 'CHEST', 'CABLE', 'Moderate load, do not force shoulder stretch.', true),
('292139cb-18c0-525f-9541-cfffaac2a0b9', 'GLOBAL', null, 'Reverse Fly (Machine)', 'Crucifixo inverso maquina', 'REAR_DELT_FLY', 'REAR_DELTS', 'MACHINE', 'Controlled movement, no rotator cuff pain.', true),
('65b71642-a32c-5d4c-b65e-fe251df10d5f', 'GLOBAL', null, 'Bicep Curl (Machine)', 'Rosca biceps maquina', 'ELBOW_FLEXION', 'BICEPS', 'MACHINE', 'Elbows supported, no swinging.', true),
('0e8c416e-932b-53dd-ab2c-a25bbe1fc060', 'GLOBAL', null, 'Lying Leg Curl (Machine)', 'Mesa flexora deitada', 'KNEE_FLEXION', 'HAMSTRINGS', 'MACHINE', 'Do not lift hips, controlled return.', true),
('f5398312-e9a6-5cdc-af9c-db3276ff4a00', 'GLOBAL', null, 'Hip Abduction (Machine)', 'Abdutora', 'HIP_ABDUCTION', 'GLUTE_MEDIUS', 'MACHINE', 'Torso still, do not rotate hip.', true),
('12b277ed-8d81-5f33-a262-ee268d87b550', 'GLOBAL', null, 'Glute Kickback (Machine)', 'Coice gluteo maquina', 'HIP_EXTENSION', 'GLUTES', 'MACHINE', 'Move through hip, no lumbar compensation.', true),
('95df1d1e-fd36-5ce4-a66a-769bcf0194ed', 'GLOBAL', null, 'Plank', 'Prancha', 'ANTI_EXTENSION_CORE', 'CORE', 'BODYWEIGHT', 'Neutral spine, stop before posture breaks.', true),
('65398b9b-9400-52f7-ae90-c022b9d9bb30', 'GLOBAL', null, 'Shoulder Press (Machine)', 'Desenvolvimento maquina', 'VERTICAL_PUSH', 'SHOULDERS', 'MACHINE', 'Neutral grip if possible, pain-free range.', true),
('81e1ecf2-b96f-58c9-b226-654c5f7ab607', 'GLOBAL', null, 'Preacher Curl (Machine)', 'Rosca Scott maquina', 'ELBOW_FLEXION', 'BICEPS', 'MACHINE', 'Fixed elbows, comfortable range.', true),
('2947d77b-5605-5d5b-a37b-fe3ad9fe76b4', 'GLOBAL', null, 'Hammer Curl (Dumbbell)', 'Rosca martelo com halteres', 'ELBOW_FLEXION', 'BICEPS', 'DUMBBELL', 'Neutral wrist, no torso swinging.', true),
('10e68ed1-cead-5c25-8ef8-2a66761a7efc', 'GLOBAL', null, 'Triceps Extension (Cable)', 'Extensao de triceps no cabo', 'ELBOW_EXTENSION', 'TRICEPS', 'CABLE', 'Fixed elbows, full control.', true),
('a1174a88-cf71-5c2b-85b7-aa10d52c7a83', 'GLOBAL', null, 'Elliptical / Transport', 'Transport / Eliptico', 'ZONE_2_CARDIO', 'CARDIO', 'CARDIO_MACHINE', 'Sustainable pace, low impact.', true),
('fa3c187d-5a64-5e07-acdc-bc508627b259', 'GLOBAL', null, 'Mobility', 'Mobilidade leve', 'MOBILITY', 'MOBILITY', 'BODYWEIGHT', 'No forced lumbar twisting, no pain.', true)
on conflict (id) do update set
    scope = excluded.scope,
    owner_user_id = excluded.owner_user_id,
    name = excluded.name,
    name_pt = excluded.name_pt,
    movement_pattern = excluded.movement_pattern,
    body_area = excluded.body_area,
    equipment_type = excluded.equipment_type,
    default_safety_notes = excluded.default_safety_notes,
    active = excluded.active,
    updated_at = current_timestamp;
