package dev.affonsera.phoenix.exercise;

public enum MovementPattern {
	HORIZONTAL_PUSH,
	INCLINE_PUSH,
	VERTICAL_PUSH,
	HORIZONTAL_PULL,
	VERTICAL_PULL,
	CHEST_FLY,
	SHOULDER_ABDUCTION,
	REAR_DELT_FLY,
	ELBOW_FLEXION,
	ELBOW_EXTENSION,
	KNEE_EXTENSION,
	KNEE_FLEXION,
	HIP_EXTENSION,
	HIP_ABDUCTION,
	UNILATERAL_SQUAT,
	CALF_RAISE,
	TRUNK_FLEXION,
	ANTI_EXTENSION_CORE,
	ZONE_2_CARDIO,
	MOBILITY
}
